---
title: C6320
ms.date: 11/04/2016
ms.topic: reference
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
ms.openlocfilehash: 6c5c67eb40ca3373b623dddbbb3cbfe1f21dc69c
ms.sourcegitcommit: a1676bf6caae05ecd698f26ed80c08828722b237
ms.translationtype: MT
ms.contentlocale: ja-JP
ms.lasthandoff: 09/29/2020
ms.locfileid: "91508760"
---
# <a name="c6320"></a>C6320

> 警告 C6320: 例外フィルター式は定数 EXCEPTION_EXECUTE_HANDLER です。 これは、処理されることを意図していない例外をマスクする可能性があります。

この警告は、__except ブロックで EXCEPTION_EXECUTE_HANDLER 定数を使用した場合の副作用を示します。 この場合、_except ブロック内のステートメントは常に、 \_ 例外を処理するために実行されます。これには、特定の関数で処理しない例外も含まれます。 例外を処理する前に、その例外を確認することをお勧めします。

## <a name="example"></a>例

次のコードでは、__except ブロックがすべての型の例外を処理しようとするので、この警告が生成されます。

```cpp
#include <stdio.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;  // might cause access violation exception
      // code ...
   }
   __except(EXCEPTION_EXECUTE_HANDLER) // warning
   {
      puts("in except");
      // code ...
   }
}
```

この警告を解決するには、次のコードに示すように、を使用し `GetExceptionCode` て、処理する前に特定の例外を確認します。

```cpp
#include <stdio.h>
#include <windows.h>
#include <excpt.h>

void f(int *p)
{
   __try
   {
      puts("in try");
      *p = 13;    // might cause access violation exception
      // code ...
   }
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
   {
      puts("in except");
      // code ...
   }
}
```

## <a name="see-also"></a>関連項目

[try-except ステートメント](../cpp/try-except-statement.md)
